apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  sql_alchemy_conn: "..."
  executor: "..."
  AIRFLOW__WEBSERVER__SECRET_KEY: "da612bf88a02036d6bbd811b8ddb9d771288fd3107502756f53b33d1fb48"
