apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  sql_alchemy_conn: "mssql+pyodbc://sa:Mudar@123@localhost:1433/Dev?driver=ODBC+Driver+17+for+SQL+Server"
  executor: "KubernetesExecutor"



