apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pa/home/guilherme/airflow/dags

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/guilherme/airflow/logs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/guilherme/airflow/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plugins-volume
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/guilherme/airflow/plugins

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: venv-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/guilherme/airflow


